### PR TITLE
factor out avatar styling

### PR DESCRIPTION
**Pull request by nat-ser**

### CODE REVIEW

**Comment by capripot** [comment]
Great, way better than previous version 👏 
Don't forget to remove also https://github.com/nat-ser/company_profiles/blob/fb8ff3527fdc484bcc9ff169ad45f95448f8e1f4/app/assets/stylesheets/_global_nav.sass from your CoPro PR

**Comment by nat-ser** [comment]
[(2) ✅📱 Mobile users should see user drop down in global nav on jobs application](https://trello.com/c/My8s5yRW/3536-2-mobile-users-should-see-user-drop-down-in-global-nav-on-jobs-application)

**Comment by nat-ser** [comment]
[(2) ✅📱 Mobile users should see user drop down in global nav on jobs application](https://trello.com/c/My8s5yRW/3536-2-mobile-users-should-see-user-drop-down-in-global-nav-on-jobs-application)

**Comment by nat-ser** [comment]
[(2) ✅📱 Mobile users should see user drop down in global nav on jobs application](https://trello.com/c/My8s5yRW/3536-2-mobile-users-should-see-user-drop-down-in-global-nav-on-jobs-application)

**Comment by nat-ser** [comment]
[(2) ✅📱 Mobile users should see user drop down in global nav on jobs application](https://trello.com/c/My8s5yRW/3536-2-mobile-users-should-see-user-drop-down-in-global-nav-on-jobs-application)

**Comment by nat-ser** [comment]
[(2) ✅📱 Mobile users should see user drop down in global nav on jobs application](https://trello.com/c/My8s5yRW/3536-2-mobile-users-should-see-user-drop-down-in-global-nav-on-jobs-application)

**Comment by nat-ser** [comment]
[(2) ✅📱 Mobile users should see user drop down in global nav on jobs application](https://trello.com/c/My8s5yRW/3536-2-mobile-users-should-see-user-drop-down-in-global-nav-on-jobs-application)

**Pull request merged**
